variable:
  profiles: dev
spring:
  application:
    name: demo-spring-consumer
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1